#!/bin/bash -u
{ set +x; } 2>/dev/null
SOURCE=$0
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
ROOTDIR=$(cd $DIR && cd ../ && pwd)

cd "$ROOTDIR"

CONFIGURATION="${1-}"
[ -n "${CONFIGURATION-}" ] || CONFIGURATION="Debug"

xcodebuild -project "./adventofcode.xcodeproj" -configuration "$CONFIGURATION" -target "adventofcode"