#!/bin/bash -u
{ set +x; } 2>/dev/null
SOURCE=$0
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
ROOTDIR=$(cd $DIR && cd ../ && pwd)

cd "$ROOTDIR"

[ -n "${CONFIGURATION-}" ] || CONFIGURATION="Debug"

outfile="build/output.$CONFIGURATION.log"

echo "*** Building... ***"
if ! script/build "$CONFIGURATION" > $outfile; then
    echo "*** Build Failed ***"
    cat $outfile
    exit 1
fi
echo "*** Build Successful ***"
build/$CONFIGURATION/adventofcode "$@"
