(defun coord (x y)
  (list :x x :y y))

(defun get-root-coord (root)
  (if (eql root 1)
      (coord 0 0)
      (if (eql root 2)
	  (coord -1 -1)
	  (let ((half-root (floor (/ root 2))))
	    (if (eql (mod root 2) 0)
		(coord (- (1- half-root)) (- half-root))
		(coord half-root half-root))))))
	
(defun find-roots (val)
  (let ((sq (sqrt val)))
    (list (floor sq) (ceiling sq))))

(defun closest-root (roots val)
  (destructuring-bind (lo hi) roots
    (let ((losq (* lo lo))
	  (hisq (* hi hi)))
      (if (eql val hisq)
	  (list hi (coord 0 0))
	  (let ((lo-break (+ losq (floor (/ (- hisq losq) 2)))))
	    (if (oddp lo)
		(if (> val lo-break)
		    (list hi (coord (- hisq val) 0))
		    (list lo (coord 1 (1+ (- (- val losq))))))
		(if (> val lo-break)
		    (list hi (coord (- (- hisq val)) 0))
		    (list lo (coord -1 (1- (- val losq)))))))))))

(defun get-coord (val)
  (destructuring-bind (root dist) (closest-root (find-roots val) val)
    (coord+ (get-root-coord root) dist)))

(defun coord+ (c1 c2)
  (let ((c1x (getf c1 :x))
	(c1y (getf c1 :y))
	(c2x (getf c2 :x))
	(c2y (getf c2 :y)))
    (coord (+ c1x c2x) (+ c1y c2y))))


(defun coord- (c1 c2)
  (let ((c1x (getf c1 :x))
	(c1y (getf c1 :y))
	(c2x (getf c2 :x))
	(c2y (getf c2 :y)))
    (coord (- c1x c2x) (- c1y c2y))))

(defun run-day3a (input)
  (let ((c (coord- (get-coord input) (coord 0 0))))
    (let ((x (getf c :x))
	  (y (getf c :y)))
      (+ (abs x) (abs y)))))
